In [1]:
import numpy as np
vetor = [1,5,9]
type(vetor)


list

In [2]:
meuvetor = np.array(vetor)

In [3]:
meuvetor


array([1, 5, 9])

In [4]:
type(meuvetor)

numpy.ndarray

In [7]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
np.zeros(shape=(4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])